name: TagBot
on:
  issue_comment:
    types:
      - created
  push:
    branches:
      - actions/trigger/TagBot
  workflow_dispatch:
jobs:
  TagBot:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.SSH_KEY }}
