name: TagBot
on:
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - actions/trigger/TagBot
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.SSH_KEY }}
